#!/usr/bin/env node
/* ═══════════════════════════════════════════════
   BARAMASI — one-time product seeder.

   Copies the bundled catalogue (js/products.js) into the
   Supabase `products` table.

   Usage:
     # 1) print idempotent SQL (paste into Supabase → SQL editor)
     node tools/seed.mjs --sql

     # 2) or push straight to Supabase using the service role key
     SUPABASE_URL=https://xyz.supabase.co \
     SUPABASE_SERVICE_ROLE_KEY=eyJ... \
     node tools/seed.mjs

   No dependencies — it talks to PostgREST over plain fetch.
   ═══════════════════════════════════════════════ */

import { PRODUCTS } from '../js/products.js';

/* a bundled product → a products-table row */
function row(p, i) {
  return {
    id: p.id,
    type: p.type,
    colour: p.colour,
    name_en: p.name.en,
    name_hi: p.name.hi,
    desc_en: p.desc.en,
    desc_hi: p.desc.hi,
    fabric_en: p.fabric.en,
    fabric_hi: p.fabric.hi,
    craft_en: p.craft.en,
    craft_hi: p.craft.hi,
    price: p.price,
    price_confirmed: p.priceConfirmed,
    stock: null,                        /* real stock is unknown for the seed */
    image_url: p.images[0] || null,
    card_url: p.cards[0] || null,
    best_seller: p.bestSeller,
    new_arrival: p.newArrival,
    availability: p.availability,
    sort_order: i,                      /* preserve the curated catalogue order */
  };
}

function sqlValue(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return `'${String(v).replace(/'/g, "''")}'`;
}

const COLS = ['id', 'type', 'colour', 'name_en', 'name_hi', 'desc_en', 'desc_hi',
  'fabric_en', 'fabric_hi', 'craft_en', 'craft_hi', 'price', 'price_confirmed',
  'stock', 'image_url', 'card_url', 'best_seller', 'new_arrival', 'availability',
  'sort_order'];

function sqlRows() {
  const rows = PRODUCTS.map((p, i) => row(p, i));
  return rows.map((r) =>
    `(${COLS.map((c) => sqlValue(r[c])).join(', ')})`).join(',\n  ');
}

function toSQL() {
  const updates = COLS.filter((c) => c !== 'id')
    .map((c) => `${c} = EXCLUDED.${c}`).join(',\n    ');
  return `-- BARAMASI seed (${PRODUCTS.length} products) — generated by tools/seed.mjs\n` +
    `INSERT INTO products (${COLS.join(', ')})\nVALUES\n  ${sqlRows()}\n` +
    `ON CONFLICT (id) DO UPDATE SET\n    ${updates};\n`;
}

async function toSupabase() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error('Missing SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY env vars.');
    process.exit(1);
  }
  const body = PRODUCTS.map((p, i) => row(p, i));
  const res = await fetch(`${url.replace(/\/$/, '')}/rest/v1/products?on_conflict=id`, {
    method: 'POST',
    headers: {
      apikey: key,
      Authorization: `Bearer ${key}`,
      'Content-Type': 'application/json',
      Prefer: 'resolution=merge-duplicates',
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    console.error('Seed failed:', res.status, await res.text());
    process.exit(1);
  }
  console.log(`Seeded ${body.length} products.`);
}

if (process.argv.includes('--sql')) {
  process.stdout.write(toSQL());
} else {
  await toSupabase();
}
